name: Mercury
markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
exclude: ["README.md", "Gruntfile.js", "node_modules", "config.rb", "package.json", "LICENSE-MIT", "bower.json"]
gems:
- jekyll-compass
- compass
